### ISSUE TITLE
FillProportionally Distribution not working as expected

### ISSUE THREAD

**Issue by nmilcoff** [Cheesebaron/TZStackView#6]
As the title says, the FillProportionally distribution seems to have a bug.

I didn't find the problem yet, but it is really easy to reproduce: 

**Reproduction sample:** Sample hosted in repo.
**Use case:** Run the sample -> Tap Horizontal option in segmented control -> Tap FillProportionally option.
**Expected behaviour:** Since all views have intrinsic content size set, all of them should be visible.
**Actual behaviour:** Only one view is displayed.

![simulator screen shot 26 mar 2017 12 32 23](https://cloud.githubusercontent.com/assets/12127846/24332628/5cc7cd98-1220-11e7-99c6-67e6c338fdae.png)

**Comment by Cheesebaron** [comment]
Thanks for reporting this. I've found the problem, fix incoming 👍

**Comment by Cheesebaron** [comment]
Will release this later tonight. Thanks again.

**Comment by nmilcoff** [comment]
Awesome! thank you :)

**Comment by Cheesebaron** [comment]
https://www.nuget.org/packages/TZStackView/1.1.1
